language: ruby
rvm:
 - 2.3.0p0
notifications:
  email: false

apt addons:
before_install:
install:
before_script:
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
after_success:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: "dc4adac0-6490-4e98-b3f0-aa1adafd0ee8"
  on: master
  run:
      - "rake db:migrate"
      - "rake cleanup"
after_deploy:
after_script:




